# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfile',
            name='type',
        ),
    ]
