# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_remove_textfile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meaning',
            name='dictionary',
        ),
    ]
